In [1]:
import pandas as pd
import numpy as np

In [3]:
T1=pd.read_csv("C:\\Users\\dhruv\\OneDrive\\Documents\\Desktop\\Dashboards_prac\\Dashboard_6\\Apple\\Apple_Financial\\apple_income_statement.csv")
T1.head()

,Unnamed: 0,2012-12-31,2013-12-31,2014-12-31,2015-12-31,2016-12-31,2017-12-31,2018-12-31,2019-12-31,2020-12-31,2021-12-31
0,Cash,0,0,0,0,0,0,0,0,0,0
1,Cash & Equivalents,5490,6081,7341,6460,7168,8261,7857,8284,9352,9254
2,Short Term Investments,29,14,0,0,0,0,1,0,0,0
3,Cash and Short Term Investments,5519,6095,7341,6460,7168,8261,7858,8284,9352,9254
4,"Accounts Receivable - Trade, Net",8831,8326,7699,6677,5919,7376,8767,8484,7317,8477

In [4]:
T1.shape

(31, 11)

In [5]:
T1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  31 non-null     object
 1   2012-12-31  31 non-null     int64
 2   2013-12-31  31 non-null     int64
 3   2014-12-31  31 non-null     int64
 4   2015-12-31  31 non-null     int64
 5   2016-12-31  31 non-null     int64
 6   2017-12-31  31 non-null     int64
 7   2018-12-31  31 non-null     int64
 8   2019-12-31  31 non-null     int64
 9   2020-12-31  31 non-null     int64
 10  2021-12-31  31 non-null     int64
dtypes: int64(10), object(1)
memory usage: 2.8+ KB

In [6]:
T1['Unnamed: 0'].unique()

array(['Cash', 'Cash & Equivalents', 'Short Term Investments',
       'Cash and Short Term Investments',
       'Accounts Receivable - Trade, Net', 'Total Receivables, Net',
       'Total Inventory', 'Other Current Assets, Total',
       'Total Current Assets', 'Property/Plant/Equipment, Total - Gross',
       'Accumulated Depreciation, Total',
       'Property/Plant/Equipment, Total - Net', 'Long Term Investments',
       'Other Long Term Assets, Total', 'Total Assets',
       'Accounts Payable', 'Notes Payable/Short Term Debt',
       'Current Port. of  LT Debt/Capital Leases',
       'Other Current liabilities, Total', 'Total Current Liabilities',
       'Long Term Debt', 'Total Long Term Debt', 'Total Debt',
       'Other Liabilities, Total', 'Total Liabilities',
       'Common Stock, Total', 'Retained Earnings (Accumulated Deficit)',
       'Unrealized Gain (Loss)', 'Other Equity, Total', 'Total Equity',
       "Total Liabilities & Shareholders' Equity"], dtype=object)

In [8]:
T1.rename(columns={'Unnamed: 0': 'Variable'}, inplace=True)

In [9]:
T1.to_csv("Apple_Fin.csv", index=False)

### Quartely

In [12]:
Q1=pd.read_csv("C:\\Users\\dhruv\\OneDrive\\Documents\\Desktop\\Dashboards_prac\\Dashboard_6\\Apple\\Apple_Quartely\\Apple_DB.csv")
Q1.head()

,Year,Date,Quarter,NetSales_Products,NetSales_Services,NetSales_Total,COG_Products,COG_Services,COG_Total,Gross_margin,...,LiabilitiesNC_Term_debt,LiabilitiesNC_Other,LiabilitiesNC_Total,Liabilities_Total,Shareholders_Equity_outstanding_respectively,Retained_earnings,Accumulated_other_comprehensive_income,Shareholders_Equity_Total,Total_liabilities_and_shareholders_equity,Stock_Price
0,2023,09/01/2023,4,67184,22314,89498,42586,6485,49071,40427,...,95281,49848,145129,290437,73812,-214,-11452,62146,352583,338.11
1,2023,06/01/2023,3,60584,21213,81797,39136,6248,45384,36413,...,98071,51730,149801,274764,70667,1408,-11801,60274,335038,335.92
2,2023,04/01/2023,2,73929,20907,94836,46795,6065,52860,41976,...,97041,52886,149927,270002,69568,4336,-11746,62158,332160,307.26
3,2022,12/01/2022,1,96388,20766,117154,60765,6057,66822,50332,...,99627,53107,152734,290020,66399,3240,-12912,56727,346747,247.81
4,2022,09/01/2022,4,70958,19188,90146,46387,5664,52051,38095,...,98959,49142,148101,302083,64849,-3068,-11109,50672,352755,232.13

In [14]:
Q2=pd.read_csv("C:\\Users\\dhruv\\OneDrive\\Documents\\Desktop\\Dashboards_prac\\Dashboard_6\\Apple\\Apple_Quartely\\Data for Training - Apple DB - Accumulated Statement.csv")
Q2.head()

,Year,2023,2023.1,2023.2,2022,2022.1,2022.2,2022.3,2021,2021.1,...,2021.3,2020,2020.1,2020.2,2020.3,2019,2019.1,2019.2,2019.3,2018
0,Date,9.2023,6.2023,04.2023,12.2023,9.2022,6.2022,3.2022,12.2021,9.2021,...,3.2021,12.2020,09.2020,06.2020,03.2020,12.2019,09.2019,06.2019,03.2019,12.2018
1,Quarter,Q4,Q3,Q2,Q1,Q4,Q3,Q2,Q1,Q4,...,Q2,Q1,Q4,Q3,Q2,Q1,Q4,Q3,Q2,Q1
2,NetSales_Products,"67,184","60,584","73,929","96,388","70,958","63,355","77,457","104,429","65,083",...,"72,683","95,678","50,149","46,529","44,965","79,104","51,529","42,354","46,565","73,435"
3,NetSales_Services,"22,314","21,213","20,907","20,766","19,188","19,604","19,821","19,516","18,277",...,"16,901","15,761","14,549","13,156","13,348","12,715","12,511","11,455","11,450","10,875"
4,NetSales_Total,"89,498","81,797","94,836","117,154","90,146","82,959","97,278","123,945","83,360",...,"89,584","111,439","64,698","59,685","58,313","91,819","64,040","53,809","58,015","84,310"

In [15]:
Q1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 48 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Year                                          20 non-null     int64
 1   Date                                          20 non-null     object
 2   Quarter                                       20 non-null     int64
 3   NetSales_Products                             20 non-null     int64
 4   NetSales_Services                             20 non-null     int64
 5   NetSales_Total                                20 non-null     int64
 6   COG_Products                                  20 non-null     int64
 7   COG_Services                                  20 non-null     int64
 8   COG_Total                                     20 non-null     int64
 9   Gross_margin                                  20 non-null     int64
 10  OperatingExpase_RND                           20 non-null     int64
 11  OperatingExpase_SGA                           20 non-null     int64
 12  OperatingExpase_Total                         20 non-null     int64
 13  Operating_income                              20 non-null     int64
 14  Other_income_expanse                          20 non-null     int64
 15  Income_before_provision_for_income_taxes      20 non-null     int64
 16  Provision_for_income_taxes                    20 non-null     int64
 17  Net_income                                    20 non-null     int64
 18  Earnings_per_share_Basic                      20 non-null     float64
 19  Earnings_per_share_Diluted                    20 non-null     float64
 20  AssetsCurrent_Cash                            20 non-null     int64
 21  AssetsCurrent_Marketable_securities           20 non-null     int64
 22  AssetsCurrent_Accounts_receivable             20 non-null     int64
 23  AssetsCurrent_Inventories                     20 non-null     int64
 24  AssetsCurrent_non_trade_receivables           20 non-null     int64
 25  AssetsCurrent_Other                           20 non-null     int64
 26  AssetsCurrent_Total                           20 non-null     int64
 27  AssetsNC_Marketable_securities                20 non-null     int64
 28  AssetsNC_PPE                                  20 non-null     int64
 29  AssetsNC_Other                                20 non-null     int64
 30  AssetsNC_Total                                20 non-null     int64
 31  Assets_Total                                  20 non-null     int64
 32  LiabilitiesCurrent_Accounts payable           20 non-null     int64
 33  LiabilitiesCurrent_Other                      20 non-null     int64
 34  LiabilitiesCurrent_Deferred_revenue           20 non-null     int64
 35  LiabilitiesCurrent_Commercial_paper           20 non-null     int64
 36  LiabilitiesCurrent_Term_debt                  20 non-null     int64
 37  LiabilitiesCurrent_Total                      20 non-null     int64
 38  LiabilitiesNC_Term_debt                       20 non-null     int64
 39  LiabilitiesNC_Other                           20 non-null     int64
 40  LiabilitiesNC_Total                           20 non-null     int64
 41  Liabilities_Total                             20 non-null     int64
 42  Shareholders_Equity_outstanding_respectively  20 non-null     int64
 43  Retained_earnings                             20 non-null     int64
 44  Accumulated_other_comprehensive_income        20 non-null     int64
 45  Shareholders_Equity_Total                     20 non-null     int64
 46  Total_liabilities_and_shareholders_equity     20 non-null     int64
 47  Stock_Price                                   20 non-null     float64
dtypes: float64(3), int64(44), object(1)
memory usage: 7.6+ KB

In [19]:
Q1['Date']=pd.to_datetime(Q1['Date'], format='%d/%m/%Y')

In [20]:
Q1.to_csv("apple_segment_revenue.csv",index=False)