In [1]:
import pandas as pd
import numpy as np

In [2]:
T1=pd.read_csv("Tesla_financial/tesla.csv")
T1.head()

,Unnamed: 0,Date,Open,High,Low,Close*,Adj Close**,Volume
0,0,"Nov 20, 2023",234.04,237.10,231.02,235.60,235.60,"115,325,704"
1,1,"Nov 17, 2023",232.00,237.39,226.54,234.30,234.30,"142,532,800"
2,2,"Nov 16, 2023",239.49,240.88,230.96,233.59,233.59,"136,816,800"
3,3,"Nov 15, 2023",239.29,246.70,236.45,242.84,242.84,"150,354,000"
4,4,"Nov 14, 2023",235.03,238.14,230.72,237.41,237.41,"149,771,600"

In [3]:
T1.shape

(100, 8)

In [4]:
T1.isnull().sum()

Unnamed: 0     0
Date           0
Open           0
High           0
Low            0
Close*         0
Adj Close**    0
Volume         0
dtype: int64

In [5]:
T1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   100 non-null    int64
 1   Date         100 non-null    object
 2   Open         100 non-null    float64
 3   High         100 non-null    float64
 4   Low          100 non-null    float64
 5   Close*       100 non-null    float64
 6   Adj Close**  100 non-null    float64
 7   Volume       100 non-null    object
dtypes: float64(5), int64(1), object(2)
memory usage: 6.4+ KB

In [6]:
T1["Volume"]=T1["Volume"].str.replace(',','').astype(int)

In [7]:
T1['Date']=pd.to_datetime(T1['Date'], format='%b %d, %Y')

In [29]:
T1.to_csv("Tesla_Financial_format.csv", index=False)

**Historical**

In [9]:
h1=pd.read_csv("Tesla_Historical/HistoricalData_1726367135218.csv")
h1.head()

         Date Close/Last    Volume     Open     High        Low
0  09/13/2024    $230.29  59515110  $228.00  $232.67    $226.32
1  09/12/2024    $229.81  72020040  $224.66  $231.45    $223.83
2  09/11/2024    $228.13  83548630  $224.55  $228.47  $216.8003
3  09/10/2024    $226.17  78891140  $220.07  $226.40  $218.6377
4  09/09/2024    $216.27  67443520  $216.20  $219.87    $213.67

In [10]:
h1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        2517 non-null   object
 1   Close/Last  2517 non-null   object
 2   Volume      2517 non-null   int64
 3   Open        2517 non-null   object
 4   High        2517 non-null   object
 5   Low         2517 non-null   object
dtypes: int64(1), object(5)
memory usage: 118.1+ KB

In [11]:
h1['Date']=pd.to_datetime(h1['Date'], format='%m/%d/%Y')

**h2**

In [12]:
h2=pd.read_csv("Tesla_Historical/tsla_2025.csv")
h2.head()

         Date     Open     High      Low    Close     Volume
0  2010-06-28  1.13333  1.13333  1.13333  1.13333          0
1  2010-06-29  1.26667  1.66667  1.16933  1.59267  281749140
2  2010-06-30  1.71933  2.02800  1.55333  1.58867  257915910
3  2010-07-01  1.66667  1.72800  1.35133  1.46400  123447945
4  2010-07-02  1.53333  1.54000  1.24733  1.28000   77127105

In [13]:
h2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3663 entries, 0 to 3662
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3663 non-null   object
 1   Open    3663 non-null   float64
 2   High    3663 non-null   float64
 3   Low     3663 non-null   float64
 4   Close   3663 non-null   float64
 5   Volume  3663 non-null   int64
dtypes: float64(4), int64(1), object(1)
memory usage: 171.8+ KB

In [14]:
h2['Date']=pd.to_datetime(h2['Date'], format='%Y-%m-%d')

**h3**

In [15]:
h3=pd.read_csv("Tesla_Historical/TSLA-2.csv")
h3.head()

         Date      Open      High       Low     Close  Adj Close     Volume
0  2010-06-29  1.266667  1.666667  1.169333  1.592667   1.592667  281494500
1  2010-06-30  1.719333  2.028000  1.553333  1.588667   1.588667  257806500
2  2010-07-01  1.666667  1.728000  1.351333  1.464000   1.464000  123282000
3  2010-07-02  1.533333  1.540000  1.247333  1.280000   1.280000   77097000
4  2010-07-06  1.333333  1.333333  1.055333  1.074000   1.074000  103003500

In [16]:
h3=h3.drop(['Adj Close'], axis=1)

In [17]:
h3.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

In [18]:
h2.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

In [19]:
h3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3562 entries, 0 to 3561
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3562 non-null   object
 1   Open    3562 non-null   float64
 2   High    3562 non-null   float64
 3   Low     3562 non-null   float64
 4   Close   3562 non-null   float64
 5   Volume  3562 non-null   int64
dtypes: float64(4), int64(1), object(1)
memory usage: 167.1+ KB

In [20]:
h3['Date']=pd.to_datetime(h3['Date'], format='%Y-%m-%d')

In [21]:
h1.shape

(2517, 6)

In [22]:
h2.shape

(3663, 6)

In [23]:
h3.shape

(3562, 6)

In [24]:
h4=pd.concat([h2,h3], ignore_index=True)

In [25]:
h4 = h4.drop_duplicates(subset='Date').sort_values('Date')

In [26]:
h4.head()

        Date     Open     High      Low    Close     Volume
0 2010-06-28  1.13333  1.13333  1.13333  1.13333          0
1 2010-06-29  1.26667  1.66667  1.16933  1.59267  281749140
2 2010-06-30  1.71933  2.02800  1.55333  1.58867  257915910
3 2010-07-01  1.66667  1.72800  1.35133  1.46400  123447945
4 2010-07-02  1.53333  1.54000  1.24733  1.28000   77127105

In [27]:
h4.isnull().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [28]:
h4.to_csv("Tesla_stock.csv", index=False)